version: '3.8'

services:
  transcoding_api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: transcoding_api
    ports:
      - "26958:80"
    volumes:
      - .:/var/www/html
      - transcoding_storage:/var/www/html/storage/app
    restart: unless-stopped
    
  transcoding_queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcoding_queue
    command: sh -lc "php artisan queue:work --queue=transcoding --tries=1 --timeout=7200 --sleep=3"
    volumes:
      - .:/var/www/html
      - transcoding_storage:/var/www/html/storage/app
    restart: unless-stopped
    depends_on:
      - transcoding_api

volumes:
  transcoding_storage:
